import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Search } from "lucide-react";
import { Film } from "lucide-react";
import { Moon } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Header = () => {
  return (
    <div className="flex justify-center my-5">
      <div className="flex flex-row justify-between w-[375px] h-[69px]">
        <div className="w-[92px] h-[20px] flex flex-row items-center justify-center gap-2 ">
          <Film />
          <span className="text-[#4338CA] text-[16px] font-[Inter] italic font-bold leading-[20px] tracking-wide">
            Movie Z
          </span>
        </div>

        <div className=" w-[84px] h-[36px] justify-between flex flex-row">
          <Search className="text-gray-500 "></Search>
          <Moon className="text-gray-500"></Moon>
        </div>
      </div>
    </div>
  );
};

const Footer = () => {
  return (
    <div className="flex justify-center">
      <div className="w-[375px] h-[308px] flex justify-center bg-indigo-700">
        <div className="w-[335px] h-[228px] my-[40px] mx-[5px] flex flex-col justify-around ">
          <div className="w-[92px] h-[20px] flex flex-row items-center justify-center gap-2 ">
            <Film className="text-[#FAFAFA]"></Film>
            <span className="text-[#FAFAFA] text-[16px] font-[Inter] italic font-bold leading-[20px] tracking-wide">
              Movie Z
            </span>
          </div>
          <div className="flex flex-col justify-between">
            <div className="w-[247px] h-[20px] text-[#FAFAFA] font-[Inter] text-[14px] font-normal leading-5">
              © 2024 Movie Z. All Rights Reserved.
            </div>
            <div className="h-[148px] w-[335px]">
              <div className="h-[104px] w-[174px] flex flex-col justify-between">
                <div className="w-[247px] h-[20px] text-[#FAFAFA] font-[Inter] text-[14px] font-normal leading-5">
                  Contact information
                </div>
                <div className="h-[40] w-[100%] text-[#FAFAFA] font-[Inter] text-[14px] font-normal leading-5">
                  support@MovieZ.com
                </div>
                <div className="h-[40] w-[100%] text-[#FAFAFA] font-[Inter] text-[14px] font-normal leading-5">
                  +976 (12) 453478
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
